version: '3.9'

services:
  nest-app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  postgres_data:
